# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Chris Wayne"
description: > # this means to ignore newlines until "email:"
   Engineering Manager - Author - Lost a bunch of weight - Overall okay dude

email: cwayne18@gmail.com
#blog logo
logo: "/assets/images/cwayne.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/header.jpg"

name: 'Chris Wayne'
author: 'Chris Wayne'
author_image: "/assets/images/cwayne.jpg"

paginate:	5

url: "http://chrismwayne.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@chrismwayne'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/chrismwayne
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/cwayne18
    desc:	Fork me on github
    share_url:
    share_title:
    share_link: